### PR TITLE
Claw

### PR DESCRIPTION
**Pull request by KinetekEnergy**
# Claw
 - Code to control the claw, color sensor
 
fixed the problems from before. new pr for review and feedback

### CODE REVIEW

**Comment by KinetekEnergy** [comment]
also we might make changes today (tuesday) and tommorow (wednesday) so be aware of that

**Comment by KinetekEnergy** [comment]
does a pr update automatically i hope it does istg

**Review by rohinsood — CHANGES_REQUESTED** [review]
You guys need to remove files that are unecessary to initial testing and add javadoc commetns according to the [Team Optix Coding Practices ](https://docs.google.com/document/d/1E-Mj6l32GF3YB4dCoeExPDwznjNDSNkzOSlMVfsQ5nw/edit
) doc I made.

**Comment by Flying-Book** [comment]
> are unecessary to initial testing and add javadoc commetns according to the [Team Optix Coding Practices ](https://docs.google.com/document/d/1E-Mj6l32GF3YB4dCoeExPDwznjNDSNkzOSlMVfsQ5nw/edit) doc I made.

Deleted Base Code + Headings Formated

**Pull request closed without merging**
